### ISSUE TITLE
Login not working anymore?

### ISSUE THREAD

**Issue by martinOpply** [filippofinke/tutti-api#3]
Hi Filippo,
first of all, great work!
I just wanted to try logging in (but translated the code into Python first) but it seems like the login is cloudflare-blocked. Is this a known issue?
Thanks!

**Comment by filippofinke** [comment]
The project is no longer maintained as it is not in use anymore. It's possible that Cloudflare has updated their protection mechanisms, which could be causing the issue you're experiencing. 

If I find the time, I might try to bypass it, but for now, there are no plans for updates.

**Comment by absztra** [comment]
Cool project! I'm getting the output {"error": {"code": "not-found"}}.
Is the API now closed or is this due to the Cloudflare protection?

**Comment by filippofinke** [comment]
> Cooles Projekt! Ich bekomme als Ausgabe `{"error": {"code": "not-found"}}`. Ist die API mittlerweile geschlossen oder ist das durch den Cloudflare Schutz?

Hi,

thanks for your message and your interest in the project!

For future issues or technical questions, it would be better to write in English, so that other developers in the community can also understand and contribute.

Regarding your question: the access APIs for tutti.ch have changed completely. At the moment, I have private solutions that are not publicly available. I might consider publishing them in the future, but for now they are not accessible.

**Comment by absztra** [comment]
Thanks for the clarification - makes sense. I'll keep an eye out in case you decide to release the new solutions in the future. In the meantime, I'll look for other ways to work with the platform. Appreciate your work on the project!
